"""
=============================================================
AGENTE v14 - Project Scaffolding Tool
=============================================================
Creates complete multi-file project structures from templates.
Allows the agent to say "create a Next.js app" and generate
ALL files at once instead of one file at a time.

Templates:
  - nextjs_app:       Next.js 14+ App Router, Tailwind, TypeScript
  - express_api:      Express.js REST API with TypeScript
  - python_cli:       Python CLI tool with argparse
  - python_api:       FastAPI REST API with SQLAlchemy
  - react_app:        React Vite app with TypeScript
  - fullstack_nextjs: Next.js full-stack with Prisma, API routes
  - python_package:   Python package with pyproject.toml

Usage:
    scaffold = ProjectScaffold()
    result = scaffold.scaffold_project("nextjs_app", "my-app")
    result = scaffold.scaffold_project("python_api", "my-api", options={"overwrite": True})
=============================================================
"""

import os
import json
import subprocess
import shlex
import re
from typing import Optional

from config import REPOS_DIR, logger
from utils.security import validate_path


# ============================================================
# TEMPLATE RENDERING HELPER
# ============================================================

# We use custom delimiters __NAME__ and __DESC__ to avoid conflicts
# with curly braces in JSON, TypeScript, CSS, etc.
# The template files are written with normal single braces everywhere,
# and only __PROJECT_NAME__ / __DESCRIPTION__ get replaced.

def _render(content: str, project_name: str, description: str = "") -> str:
    """Replace __PROJECT_NAME__ and __DESCRIPTION__ placeholders in template content.

    Uses str.replace() with unique delimiters to avoid any conflict with
    curly braces in JSON, TypeScript, CSS, etc.
    """
    return (
        content
        .replace("__PROJECT_NAME__", project_name)
        .replace("__DESCRIPTION__", description or project_name)
        .replace("__PROJECT_NAME_HYPHEN__", project_name.replace("_", "-"))
        .replace("__PROJECT_NAME_UNDERSCORE__", project_name.replace("-", "_"))
    )


# ============================================================
# COMPLETE WORKING TEMPLATES
# ============================================================

TEMPLATES = {
    # --------------------------------------------------------
    # NEXT.JS 14+ APP ROUTER
    # --------------------------------------------------------
    "nextjs_app": {
        "name": "nextjs_app",
        "description": "Next.js 14+ App Router with TypeScript and Tailwind CSS",
        "files": {
            "package.json": """{
  "name": "__PROJECT_NAME_HYPHEN__",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.15",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.15",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.4.5"
  }
}
""",

            "src/app/layout.tsx": """import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "__DESCRIPTION__",
  description: "Generated by AgentLocal Project Scaffold",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
""",

            "src/app/page.tsx": """export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-center text-sm">
        <h1 className="text-4xl font-bold text-center mb-8">
          Welcome to <span className="text-blue-600">__PROJECT_NAME__</span>
        </h1>
        <p className="text-center text-gray-500 mb-8">
          __DESCRIPTION__
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="border rounded-lg p-6 hover:border-blue-500 transition-colors">
            <h2 className="text-xl font-semibold mb-2">Docs</h2>
            <p className="text-gray-500">
              Find in-depth information about Next.js features and API.
            </p>
          </div>
          <div className="border rounded-lg p-6 hover:border-blue-500 transition-colors">
            <h2 className="text-xl font-semibold mb-2">Learn</h2>
            <p className="text-gray-500">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </div>
          <div className="border rounded-lg p-6 hover:border-blue-500 transition-colors">
            <h2 className="text-xl font-semibold mb-2">Deploy</h2>
            <p className="text-gray-500">
              Instantly deploy your Next.js site to a shareable URL.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
""",

            "src/app/globals.css": """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}
""",

            "tsconfig.json": """{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",

            "next.config.ts": """import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
""",

            "tailwind.config.ts": """import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
""",

            "postcss.config.mjs": """/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
""",

            ".gitignore": """# dependencies
/node_modules
/.pnp
.pnp.js
.yarn/install-state.gz

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Getting Started

First, install the dependencies:

```bash
npm install
```

Then, run the development server:

```bash
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

You can start editing the page by modifying `src/app/page.tsx`. The page auto-updates as you edit the file.

## Learn More

- [Next.js Documentation](https://nextjs.org/docs)
- [Learn Next.js](https://nextjs.org/learn)
- [Tailwind CSS](https://tailwindcss.com)

## Deploy

The easiest way to deploy your Next.js app is to use [Vercel](https://vercel.com/new).
""",
        },
        "post_create_commands": ["npm install"],
        "entry_points": ["src/app/page.tsx", "src/app/layout.tsx"],
    },

    # --------------------------------------------------------
    # EXPRESS API WITH TYPESCRIPT
    # --------------------------------------------------------
    "express_api": {
        "name": "express_api",
        "description": "Express.js REST API with TypeScript, CORS, and example CRUD routes",
        "files": {
            "package.json": """{
  "name": "__PROJECT_NAME_HYPHEN__",
  "version": "1.0.0",
  "description": "__DESCRIPTION__",
  "main": "dist/index.js",
  "scripts": {
    "dev": "ts-node-dev --respawn src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js",
    "lint": "eslint src/**/*.ts"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "uuid": "^10.0.0"
  },
  "devDependencies": {
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.21",
    "@types/node": "^20.14.0",
    "@types/uuid": "^10.0.0",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.4.5"
  }
}
""",

            "tsconfig.json": """{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
""",

            ".env": """PORT=3001
NODE_ENV=development
""",

            ".gitignore": """node_modules/
dist/
.env
*.js.map
.DS_Store
coverage/
""",

            "src/index.ts": """import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import itemsRouter from './routes/items';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Request logging middleware
app.use((req: Request, res: Response, next: NextFunction) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    console.log(`${req.method} ${req.originalUrl} -> ${res.statusCode} [${duration}ms]`);
  });
  next();
});

// Routes
app.use('/api/items', itemsRouter);

// Health check
app.get('/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Root endpoint
app.get('/', (_req: Request, res: Response) => {
  res.json({
    name: '__PROJECT_NAME__',
    version: '1.0.0',
    description: '__DESCRIPTION__',
    endpoints: {
      health: 'GET /health',
      items: 'GET/POST /api/items',
      itemById: 'GET/PUT/DELETE /api/items/:id',
    },
  });
});

// 404 handler
app.use((req: Request, res: Response) => {
  res.status(404).json({ error: 'Not found', path: req.originalUrl });
});

// Error handler
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
  console.error('Unhandled error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
  console.log(`API docs: http://localhost:${PORT}/`);
});

export default app;
""",

            "src/routes/items.ts": """import { Router, Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';

const router = Router();

// In-memory store (replace with database in production)
interface Item {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

let items: Item[] = [];

// GET /api/items - List all items
router.get('/', (_req: Request, res: Response) => {
  const { search, limit = '10', offset = '0' } = _req.query;
  let result = items;

  if (search) {
    const q = String(search).toLowerCase();
    result = result.filter(
      (item) => item.name.toLowerCase().includes(q) || item.description.toLowerCase().includes(q)
    );
  }

  const start = parseInt(String(offset), 10);
  const end = start + parseInt(String(limit), 10);
  const paginated = result.slice(start, end);

  res.json({
    data: paginated,
    total: result.length,
    limit: parseInt(String(limit), 10),
    offset: start,
  });
});

// GET /api/items/:id - Get single item
router.get('/:id', (req: Request, res: Response) => {
  const item = items.find((i) => i.id === req.params.id);
  if (!item) {
    return res.status(404).json({ error: 'Item not found' });
  }
  res.json(item);
});

// POST /api/items - Create item
router.post('/', (req: Request, res: Response) => {
  const { name, description } = req.body;

  if (!name || typeof name !== 'string') {
    return res.status(400).json({ error: 'name is required and must be a string' });
  }

  const now = new Date().toISOString();
  const item: Item = {
    id: uuidv4(),
    name: name.trim(),
    description: (description || '').trim(),
    createdAt: now,
    updatedAt: now,
  };

  items.push(item);
  res.status(201).json(item);
});

// PUT /api/items/:id - Update item
router.put('/:id', (req: Request, res: Response) => {
  const index = items.findIndex((i) => i.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: 'Item not found' });
  }

  const { name, description } = req.body;
  const item = items[index];

  items[index] = {
    ...item,
    name: name !== undefined ? String(name).trim() : item.name,
    description: description !== undefined ? String(description).trim() : item.description,
    updatedAt: new Date().toISOString(),
  };

  res.json(items[index]);
});

// DELETE /api/items/:id - Delete item
router.delete('/:id', (req: Request, res: Response) => {
  const index = items.findIndex((i) => i.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: 'Item not found' });
  }

  const deleted = items.splice(index, 1)[0];
  res.json({ message: 'Item deleted', id: deleted.id });
});

export default router;
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Quick Start

```bash
npm install
npm run dev
```

Server starts at http://localhost:3001

## API Endpoints

| Method | Endpoint          | Description        |
|--------|-------------------|--------------------|
| GET    | /health           | Health check       |
| GET    | /api/items        | List all items     |
| GET    | /api/items/:id    | Get item by ID     |
| POST   | /api/items        | Create new item    |
| PUT    | /api/items/:id    | Update item        |
| DELETE | /api/items/:id    | Delete item        |

## Query Parameters

- `search` - Filter items by name/description
- `limit` - Number of items per page (default: 10)
- `offset` - Number of items to skip (default: 0)

## Example Requests

```bash
# Create an item
curl -X POST http://localhost:3001/api/items \\
  -H "Content-Type: application/json" \\
  -d '{"name": "My Item", "description": "A test item"}'

# List all items
curl http://localhost:3001/api/items

# Search items
curl "http://localhost:3001/api/items?search=test&limit=5"
```

## Build for Production

```bash
npm run build
npm start
```
""",
        },
        "post_create_commands": ["npm install"],
        "entry_points": ["src/index.ts", "src/routes/items.ts"],
    },

    # --------------------------------------------------------
    # PYTHON CLI TOOL
    # --------------------------------------------------------
    "python_cli": {
        "name": "python_cli",
        "description": "Python CLI tool with argparse, subcommands, and structured output",
        "files": {
            "main.py": """#!/usr/bin/env python3
\"\"\"
__PROJECT_NAME__ - __DESCRIPTION__

A command-line tool built with argparse.
\"\"\"

import argparse
import json
import sys
import os
from datetime import datetime


VERSION = "0.1.0"


def cmd_greet(args):
    \"\"\"Greet someone.\"\"\"
    name = args.name or "World"
    greeting = f"Hello, {name}!"
    if args.upper:
        greeting = greeting.upper()
    if args.json_output:
        print(json.dumps({"greeting": greeting, "name": name}))
    else:
        print(greeting)


def cmd_info(args):
    \"\"\"Show system/environment info.\"\"\"
    info = {
        "program": "__PROJECT_NAME__",
        "version": VERSION,
        "python": sys.version,
        "platform": sys.platform,
        "cwd": os.getcwd(),
        "timestamp": datetime.now().isoformat(),
    }
    if args.json_output:
        print(json.dumps(info, indent=2))
    else:
        for key, value in info.items():
            print(f"  {key:>12}: {value}")


def cmd_config(args):
    \"\"\"Manage configuration.\"\"\"
    config_path = os.path.expanduser("~/.__PROJECT_NAME_UNDERSCORE__/config.json")

    if args.action == "show":
        if os.path.exists(config_path):
            with open(config_path) as f:
                config = json.load(f)
            print(json.dumps(config, indent=2))
        else:
            print("No configuration file found. Use 'config init' to create one.")

    elif args.action == "init":
        config_dir = os.path.dirname(config_path)
        os.makedirs(config_dir, exist_ok=True)
        default_config = {
            "version": VERSION,
            "created_at": datetime.now().isoformat(),
            "settings": {
                "output_format": "text",
                "verbose": False,
            },
        }
        with open(config_path, "w") as f:
            json.dump(default_config, f, indent=2)
        print(f"Configuration created at {config_path}")

    elif args.action == "set":
        if not args.key or not args.value:
            print("Error: --key and --value are required for 'config set'")
            sys.exit(1)
        if os.path.exists(config_path):
            with open(config_path) as f:
                config = json.load(f)
        else:
            config = {}
        keys = args.key.split(".")
        obj = config
        for k in keys[:-1]:
            obj = obj.setdefault(k, {})
        obj[keys[-1]] = args.value
        with open(config_path, "w") as f:
            json.dump(config, f, indent=2)
        print(f"Set {args.key} = {args.value}")


def build_parser():
    \"\"\"Build the argument parser with subcommands.\"\"\"
    parser = argparse.ArgumentParser(
        prog="__PROJECT_NAME__",
        description="__DESCRIPTION__",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    parser.add_argument(
        "-j", "--json",
        dest="json_output",
        action="store_true",
        help="Output in JSON format",
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # greet subcommand
    greet_parser = subparsers.add_parser("greet", help="Greet someone")
    greet_parser.add_argument("name", nargs="?", default="World", help="Name to greet")
    greet_parser.add_argument("-u", "--upper", action="store_true", help="Uppercase output")
    greet_parser.set_defaults(func=cmd_greet)

    # info subcommand
    info_parser = subparsers.add_parser("info", help="Show system info")
    info_parser.set_defaults(func=cmd_info)

    # config subcommand
    config_parser = subparsers.add_parser("config", help="Manage configuration")
    config_parser.add_argument("action", choices=["show", "init", "set"], help="Config action")
    config_parser.add_argument("--key", help="Config key (dot notation)")
    config_parser.add_argument("--value", help="Config value")
    config_parser.set_defaults(func=cmd_config)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    if hasattr(args, "func"):
        args.func(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
""",

            "requirements.txt": """# __PROJECT_NAME__ dependencies
# No external dependencies required for core functionality.
# Add your dependencies below:
# requests>=2.31.0
# rich>=13.7.0
""",

            ".gitignore": """__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
.eggs/
*.egg
.env
.venv/
venv/
.mypy_cache/
.pytest_cache/
.coverage
htmlcov/
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Installation

```bash
pip install -r requirements.txt
```

## Usage

```bash
# Show help
python main.py --help

# Greet someone
python main.py greet "Alice"
python main.py greet "Alice" --upper

# System info
python main.py info
python main.py info --json

# Configuration
python main.py config init
python main.py config show
python main.py config set --key settings.verbose --value true
```

## Development

```bash
# Run directly
python main.py greet World

# Make executable (Unix)
chmod +x main.py
./main.py info
```
""",
        },
        "post_create_commands": [],
        "entry_points": ["main.py"],
    },

    # --------------------------------------------------------
    # FASTAPI REST API
    # --------------------------------------------------------
    "python_api": {
        "name": "python_api",
        "description": "FastAPI REST API with SQLAlchemy, CORS, and example CRUD routes",
        "files": {
            "main.py": """\"\"\"
__PROJECT_NAME__ - __DESCRIPTION__

FastAPI application with SQLAlchemy ORM and CORS support.
\"\"\"

import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

from database import engine, Base, get_db
from models import Item
from routes import router as items_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    \"\"\"Startup/shutdown lifecycle.\"\"\"
    # Create tables on startup
    Base.metadata.create_all(bind=engine)
    print("Database tables created.")
    yield
    print("Shutting down...")


app = FastAPI(
    title="__PROJECT_NAME__",
    description="__DESCRIPTION__",
    version="0.1.0",
    lifespan=lifespan,
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routes
app.include_router(items_router, prefix="/api", tags=["items"])


@app.get("/")
def root():
    return {
        "name": "__PROJECT_NAME__",
        "version": "0.1.0",
        "docs": "/docs",
        "health": "/health",
    }


@app.get("/health")
def health_check():
    return {"status": "ok"}


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
""",

            "models.py": """\"\"\"SQLAlchemy models for __PROJECT_NAME__.\"\"\"

from sqlalchemy import Column, Integer, String, Text, DateTime, func
from database import Base


class Item(Base):
    \"\"\"Example Item model.\"\"\"
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False, index=True)
    description = Column(Text, default="")
    status = Column(String(50), default="active")
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
""",

            "database.py": """\"\"\"Database configuration for __PROJECT_NAME__.\"\"\"

import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, DeclarativeBase

# Default to SQLite for development; override with DATABASE_URL for production
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./__PROJECT_NAME__.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {},
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    \"\"\"Dependency that provides a database session.\"\"\"
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
""",

            "schemas.py": """\"\"\"Pydantic schemas for __PROJECT_NAME__.\"\"\"

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class ItemCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=255, description="Item name")
    description: str = Field(default="", max_length=2000, description="Item description")
    status: str = Field(default="active", pattern=r"^(active|inactive|archived)$")


class ItemUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=2000)
    status: Optional[str] = Field(None, pattern=r"^(active|inactive|archived)$")


class ItemResponse(BaseModel):
    id: int
    name: str
    description: str
    status: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class ItemListResponse(BaseModel):
    data: list[ItemResponse]
    total: int
    limit: int
    offset: int
""",

            "routes.py": """\"\"\"API routes for __PROJECT_NAME__.\"\"\"

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import Optional

from database import get_db
from models import Item
from schemas import ItemCreate, ItemUpdate, ItemResponse, ItemListResponse

router = APIRouter()


@router.get("/items", response_model=ItemListResponse)
def list_items(
    search: Optional[str] = Query(None, description="Search in name/description"),
    status: Optional[str] = Query(None, description="Filter by status"),
    limit: int = Query(10, ge=1, le=100),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    \"\"\"List all items with optional search and pagination.\"\"\"
    query = db.query(Item)

    if search:
        search_term = f"%{search}%"
        query = query.filter(
            (Item.name.ilike(search_term)) | (Item.description.ilike(search_term))
        )

    if status:
        query = query.filter(Item.status == status)

    total = query.count()
    items = query.order_by(Item.created_at.desc()).offset(offset).limit(limit).all()

    return ItemListResponse(
        data=[ItemResponse.model_validate(item) for item in items],
        total=total,
        limit=limit,
        offset=offset,
    )


@router.get("/items/{item_id}", response_model=ItemResponse)
def get_item(item_id: int, db: Session = Depends(get_db)):
    \"\"\"Get a single item by ID.\"\"\"
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return ItemResponse.model_validate(item)


@router.post("/items", response_model=ItemResponse, status_code=201)
def create_item(item_data: ItemCreate, db: Session = Depends(get_db)):
    \"\"\"Create a new item.\"\"\"
    item = Item(**item_data.model_dump())
    db.add(item)
    db.commit()
    db.refresh(item)
    return ItemResponse.model_validate(item)


@router.put("/items/{item_id}", response_model=ItemResponse)
def update_item(item_id: int, item_data: ItemUpdate, db: Session = Depends(get_db)):
    \"\"\"Update an existing item.\"\"\"
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")

    update_data = item_data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(item, field, value)

    db.commit()
    db.refresh(item)
    return ItemResponse.model_validate(item)


@router.delete("/items/{item_id}")
def delete_item(item_id: int, db: Session = Depends(get_db)):
    \"\"\"Delete an item.\"\"\"
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")

    db.delete(item)
    db.commit()
    return {"message": "Item deleted", "id": item_id}
""",

            "requirements.txt": """fastapi>=0.111.0
uvicorn[standard]>=0.30.0
sqlalchemy>=2.0.30
pydantic>=2.7.0
""",

            ".env": """# Database URL (SQLite by default, PostgreSQL for production)
# DATABASE_URL=postgresql://user:password@localhost:5432/__PROJECT_NAME_UNDERSCORE__
""",

            ".gitignore": """__pycache__/
*.py[cod]
*.db
*.sqlite3
.env
.venv/
venv/
.mypy_cache/
.pytest_cache/
.coverage
htmlcov/
dist/
build/
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Quick Start

```bash
pip install -r requirements.txt
python main.py
```

API starts at http://localhost:8000

Interactive docs available at:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## API Endpoints

| Method | Endpoint             | Description        |
|--------|----------------------|--------------------|
| GET    | /                    | API info           |
| GET    | /health              | Health check       |
| GET    | /api/items           | List items         |
| GET    | /api/items/:id       | Get item by ID     |
| POST   | /api/items           | Create item        |
| PUT    | /api/items/:id       | Update item        |
| DELETE | /api/items/:id       | Delete item        |

## Example Requests

```bash
# Create an item
curl -X POST http://localhost:8000/api/items \\
  -H "Content-Type: application/json" \\
  -d '{"name": "My Item", "description": "A test item"}'

# List items with search
curl "http://localhost:8000/api/items?search=test&limit=5"

# Get single item
curl http://localhost:8000/api/items/1
```

## Database

By default uses SQLite. For production, set `DATABASE_URL` in `.env`:

```
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
```
""",
        },
        "post_create_commands": ["pip install -r requirements.txt"],
        "entry_points": ["main.py", "models.py", "routes.py"],
    },

    # --------------------------------------------------------
    # REACT VITE APP
    # --------------------------------------------------------
    "react_app": {
        "name": "react_app",
        "description": "React Vite app with TypeScript and Tailwind CSS",
        "files": {
            "package.json": """{
  "name": "__PROJECT_NAME_HYPHEN__",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.5.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "autoprefixer": "^10.4.19",
    "eslint": "^9.5.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "globals": "^15.6.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.5.3",
    "typescript-eslint": "^8.0.0-alpha.30",
    "vite": "^5.3.1"
  }
}
""",

            "index.html": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__DESCRIPTION__</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
""",

            "vite.config.ts": """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true,
  },
})
""",

            "tsconfig.json": """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src"]
}
""",

            "tsconfig.app.json": """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
""",

            "src/main.tsx": """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
""",

            "src/App.tsx": """import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="min-h-screen bg-white flex flex-col items-center justify-center">
      <h1 className="text-5xl font-bold mb-4 text-blue-600">__PROJECT_NAME__</h1>
      <p className="text-gray-500 mb-8 text-lg">__DESCRIPTION__</p>

      <div className="bg-gray-50 rounded-2xl p-8 shadow-sm border border-gray-200">
        <button
          onClick={() => setCount((count) => count + 1)}
          className="bg-blue-600 hover:bg-blue-700 text-white font-medium px-6 py-3 rounded-lg transition-colors"
        >
          Count is {count}
        </button>
        <p className="mt-4 text-sm text-gray-500">
          Edit <code className="bg-gray-100 px-1 rounded text-sm">src/App.tsx</code> and save to test HMR
        </p>
      </div>

      <p className="mt-8 text-sm text-gray-400">
        Click the button to get started
      </p>
    </div>
  )
}

export default App
""",

            "src/index.css": """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color: #213547;
  background-color: #ffffff;
  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
""",

            "tailwind.config.js": """/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
""",

            "postcss.config.js": """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
""",

            "public/vite.svg": """<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--logos" width="31.88" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 257"><defs><linearGradient id="IconifyId1813088fe1fbc01fb466" x1="-.828%" x2="57.636%" y1="7.652%" y2="78.411%"><stop offset="0%" stop-color="#41D1FF"></stop><stop offset="100%" stop-color="#BD34FE"></stop></linearGradient><linearGradient id="IconifyId1813088fe1fbc01fb467" x1="43.376%" x2="50.316%" y1="2.242%" y2="89.03%"><stop offset="0%" stop-color="#FFBD4F"></stop><stop offset="100%" stop-color="#FF9640"></stop></linearGradient></defs><path fill="url(#IconifyId1813088fe1fbc01fb466)" d="M255.153 37.938L134.897 252.976c-2.483 4.44-8.862 4.466-11.382.048L.875 37.958c-2.746-4.814 1.371-10.646 6.827-9.67l120.385 21.517a6.537 6.537 0 0 0 2.322-.004l117.867-21.483c5.438-.991 9.574 4.796 6.877 9.62Z"></path><path fill="url(#IconifyId1813088fe1fbc01fb467)" d="M185.432.063L96.44 17.501a3.268 3.268 0 0 0-2.634 3.014l-5.474 92.456a3.268 3.268 0 0 0 3.997 3.378l24.777-5.718c2.318-.535 4.413 1.507 3.936 3.838l-7.361 36.047c-.495 2.426 1.782 4.5 4.151 3.78l15.304-4.649c2.372-.72 4.652 1.36 4.15 3.788l-11.698 56.621c-.732 3.542 3.979 5.473 5.943 2.437l1.313-2.028l72.516-144.72c1.215-2.423-.88-5.186-3.54-4.672l-25.505 4.922c-2.396.462-4.435-1.77-3.759-4.114l16.646-57.705c.677-2.35-1.37-4.583-3.769-4.113Z"></path></svg>
""",

            ".gitignore": """# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Quick Start

```bash
npm install
npm run dev
```

Open http://localhost:5173 in your browser.

## Scripts

- `npm run dev` - Start development server
- `npm run build` - Build for production
- `npm run preview` - Preview production build
- `npm run lint` - Run ESLint

## Tech Stack

- **React 18** - UI library
- **TypeScript** - Type safety
- **Vite 5** - Build tool
- **Tailwind CSS 3** - Utility-first CSS
""",
        },
        "post_create_commands": ["npm install"],
        "entry_points": ["src/App.tsx", "src/main.tsx"],
    },

    # --------------------------------------------------------
    # FULLSTACK NEXT.JS WITH PRISMA
    # --------------------------------------------------------
    "fullstack_nextjs": {
        "name": "fullstack_nextjs",
        "description": "Next.js 14+ full-stack app with Prisma ORM, API routes, and TypeScript",
        "files": {
            "package.json": """{
  "name": "__PROJECT_NAME_HYPHEN__",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "db:generate": "prisma generate",
    "db:push": "prisma db push",
    "db:studio": "prisma studio",
    "db:migrate": "prisma migrate dev",
    "db:seed": "tsx prisma/seed.ts",
    "postinstall": "prisma generate"
  },
  "dependencies": {
    "@prisma/client": "^5.16.0",
    "next": "14.2.15",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.15",
    "postcss": "^8.4.38",
    "prisma": "^5.16.0",
    "tailwindcss": "^3.4.4",
    "tsx": "^4.15.0",
    "typescript": "^5.4.5"
  }
}
""",

            "prisma/schema.prisma": """generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  name      String?
  avatar    String?
  posts     Post[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
""",

            "prisma/seed.ts": """import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Create a user
  const user = await prisma.user.upsert({
    where: { email: 'demo@__PROJECT_NAME_HYPHEN__.com' },
    update: {},
    create: {
      email: 'demo@__PROJECT_NAME_HYPHEN__.com',
      name: 'Demo User',
    },
  });

  // Create a sample post
  const post = await prisma.post.create({
    data: {
      title: 'Welcome to __PROJECT_NAME__',
      content: 'This is your first post. Edit or delete it, then start building!',
      published: true,
      authorId: user.id,
    },
  });

  console.log('Seeded:', { user, post });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
""",

            "lib/prisma.ts": """import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

export default prisma;
""",

            ".env": """# Database
DATABASE_URL="file:./dev.db"
""",

            "src/app/layout.tsx": """import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "__DESCRIPTION__",
  description: "Full-stack Next.js app with Prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
""",

            "src/app/page.tsx": """import prisma from "@/lib/prisma";

async function getPosts() {
  const posts = await prisma.post.findMany({
    where: { published: true },
    include: { author: true },
    orderBy: { createdAt: "desc" },
  });
  return posts;
}

export default async function Home() {
  const posts = await getPosts();

  return (
    <main className="min-h-screen max-w-4xl mx-auto p-8">
      <h1 className="text-4xl font-bold mb-2">__PROJECT_NAME__</h1>
      <p className="text-gray-500 mb-8">__DESCRIPTION__</p>

      <div className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Posts</h2>
        {posts.length === 0 ? (
          <p className="text-gray-400">No posts yet. Run the seed script to add sample data.</p>
        ) : (
          <div className="space-y-4">
            {posts.map((post) => (
              <article key={post.id} className="border rounded-lg p-4 hover:border-blue-500 transition-colors">
                <h3 className="text-lg font-medium">{post.title}</h3>
                {post.content && <p className="text-gray-600 mt-1">{post.content}</p>}
                <div className="text-sm text-gray-400 mt-2">
                  By {post.author.name || post.author.email} on {post.createdAt.toLocaleDateString()}
                </div>
              </article>
            ))}
          </div>
        )}
      </div>

      <div className="border-t pt-8">
        <h2 className="text-2xl font-semibold mb-4">API Endpoints</h2>
        <div className="space-y-2 text-sm">
          <div className="flex gap-4">
            <code className="bg-gray-100 px-2 py-1 rounded">GET /api/users</code>
            <span className="text-gray-500">List all users</span>
          </div>
          <div className="flex gap-4">
            <code className="bg-gray-100 px-2 py-1 rounded">POST /api/users</code>
            <span className="text-gray-500">Create a user</span>
          </div>
          <div className="flex gap-4">
            <code className="bg-gray-100 px-2 py-1 rounded">GET /api/posts</code>
            <span className="text-gray-500">List all posts</span>
          </div>
          <div className="flex gap-4">
            <code className="bg-gray-100 px-2 py-1 rounded">POST /api/posts</code>
            <span className="text-gray-500">Create a post</span>
          </div>
        </div>
      </div>
    </main>
  );
}
""",

            "src/app/globals.css": """@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, sans-serif;
}
""",

            "src/app/api/users/route.ts": """import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { z } from 'zod';

const CreateUserSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
});

export async function GET() {
  const users = await prisma.user.findMany({
    select: { id: true, email: true, name: true, createdAt: true },
    orderBy: { createdAt: 'desc' },
  });
  return NextResponse.json(users);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const data = CreateUserSchema.parse(body);

    const user = await prisma.user.create({
      data,
      select: { id: true, email: true, name: true, createdAt: true },
    });

    return NextResponse.json(user, { status: 201 });
  } catch (error: unknown) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.errors }, { status: 400 });
    }
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
""",

            "src/app/api/posts/route.ts": """import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { z } from 'zod';

const CreatePostSchema = z.object({
  title: z.string().min(1),
  content: z.string().optional(),
  published: z.boolean().optional().default(false),
  authorEmail: z.string().email(),
});

export async function GET() {
  const posts = await prisma.post.findMany({
    include: { author: { select: { name: true, email: true } } },
    orderBy: { createdAt: 'desc' },
  });
  return NextResponse.json(posts);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const data = CreatePostSchema.parse(body);

    const post = await prisma.post.create({
      data: {
        title: data.title,
        content: data.content,
        published: data.published,
        author: {
          connect: { email: data.authorEmail },
        },
      },
      include: { author: { select: { name: true, email: true } } },
    });

    return NextResponse.json(post, { status: 201 });
  } catch (error: unknown) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.errors }, { status: 400 });
    }
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
""",

            "tsconfig.json": """{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",

            "next.config.ts": """import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
""",

            "tailwind.config.ts": """import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
""",

            "postcss.config.mjs": """/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
""",

            ".gitignore": """# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# prisma
prisma/dev.db
prisma/dev.db-journal

# misc
.DS_Store
*.pem

# debug
npm-debug.log*

# local env files
.env*.local
.env

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__ — Full-stack Next.js app with Prisma ORM.

## Quick Start

```bash
npm install
npm run db:push
npm run db:seed
npm run dev
```

Open http://localhost:3000

## Database

Uses SQLite by default (no setup needed). To switch to PostgreSQL,
update `DATABASE_URL` in `.env` and the `provider` in `prisma/schema.prisma`.

### Prisma Commands

```bash
npm run db:generate   # Generate Prisma Client
npm run db:push       # Push schema to database
npm run db:migrate    # Run migrations
npm run db:studio     # Open Prisma Studio
npm run db:seed       # Seed sample data
```

## API Routes

| Method | Endpoint       | Description    |
|--------|---------------|----------------|
| GET    | /api/users    | List users     |
| POST   | /api/users    | Create user    |
| GET    | /api/posts    | List posts     |
| POST   | /api/posts    | Create post    |

### Example: Create a User

```bash
curl -X POST http://localhost:3000/api/users \\
  -H "Content-Type: application/json" \\
  -d '{"email": "user@example.com", "name": "John"}'
```

### Example: Create a Post

```bash
curl -X POST http://localhost:3000/api/posts \\
  -H "Content-Type: application/json" \\
  -d '{"title": "Hello", "content": "World", "authorEmail": "demo@__PROJECT_NAME_HYPHEN__.com"}'
```

## Deploy

Deploy to [Vercel](https://vercel.com) and set `DATABASE_URL` in environment variables.
""",
        },
        "post_create_commands": ["npm install"],
        "entry_points": ["src/app/page.tsx", "src/app/api/users/route.ts", "src/app/api/posts/route.ts", "prisma/schema.prisma"],
    },

    # --------------------------------------------------------
    # PYTHON PACKAGE
    # --------------------------------------------------------
    "python_package": {
        "name": "python_package",
        "description": "Python package with pyproject.toml, CLI entry point, and test suite",
        "files": {
            "pyproject.toml": """[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "__PROJECT_NAME_HYPHEN__"
version = "0.1.0"
description = "__DESCRIPTION__"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Developer", email = "dev@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
    "ruff>=0.4",
    "mypy>=1.10",
]

[project.scripts]
__PROJECT_NAME_HYPHEN__ = "__PROJECT_NAME_UNDERSCORE__.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

[tool.mypy]
python_version = "3.10"
strict = true
""",

            "src/__PROJECT_NAME_UNDERSCORE__/__init__.py": """\"\"\"__PROJECT_NAME__ - __DESCRIPTION__.\"\"\"

__version__ = "0.1.0"
""",

            "src/__PROJECT_NAME_UNDERSCORE__/core.py": """\"\"\"Core logic for __PROJECT_NAME__.\"\"\"

from typing import Any


def greet(name: str = "World") -> str:
    \"\"\"Return a greeting message.

    Args:
        name: The name to greet.

    Returns:
        A greeting string.
    \"\"\"
    return f"Hello, {name}!"


def process_data(data: dict[str, Any]) -> dict[str, Any]:
    \"\"\"Process input data and return enriched result.

    Args:
        data: Input dictionary to process.

    Returns:
        Processed dictionary with additional metadata.
    \"\"\"
    return {
        "original": data,
        "processed": True,
        "keys": list(data.keys()),
        "count": len(data),
    }


def validate_input(value: Any, expected_type: type) -> bool:
    \"\"\"Validate that a value matches an expected type.

    Args:
        value: The value to check.
        expected_type: The expected Python type.

    Returns:
        True if value matches expected type.
    \"\"\"
    return isinstance(value, expected_type)
""",

            "src/__PROJECT_NAME_UNDERSCORE__/cli.py": """\"\"\"CLI entry point for __PROJECT_NAME__.\"\"\"

import argparse
import json
import sys

from .core import greet, process_data
from . import __version__


def main() -> None:
    \"\"\"Main CLI entry point.\"\"\"
    parser = argparse.ArgumentParser(
        prog="__PROJECT_NAME_HYPHEN__",
        description="__DESCRIPTION__",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # greet command
    greet_parser = subparsers.add_parser("greet", help="Print a greeting")
    greet_parser.add_argument("name", nargs="?", default="World", help="Name to greet")
    greet_parser.add_argument("--json", action="store_true", help="Output as JSON")

    # process command
    process_parser = subparsers.add_parser("process", help="Process JSON data")
    process_parser.add_argument("data", help="JSON string to process")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    if args.command == "greet":
        result = greet(args.name)
        if args.json:
            print(json.dumps({"greeting": result}))
        else:
            print(result)

    elif args.command == "process":
        try:
            data = json.loads(args.data)
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON: {e}", file=sys.stderr)
            sys.exit(1)
        result = process_data(data)
        print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
""",

            "tests/__init__.py": "",

            "tests/test_core.py": """\"\"\"Tests for __PROJECT_NAME__ core module.\"\"\"

import pytest
from __PROJECT_NAME_UNDERSCORE__.core import greet, process_data, validate_input


class TestGreet:
    def test_default_greeting(self):
        assert greet() == "Hello, World!"

    def test_custom_greeting(self):
        assert greet("Alice") == "Hello, Alice!"

    def test_empty_name(self):
        assert greet("") == "Hello, !"


class TestProcessData:
    def test_empty_dict(self):
        result = process_data({})
        assert result["processed"] is True
        assert result["count"] == 0
        assert result["keys"] == []

    def test_with_data(self):
        data = {"a": 1, "b": 2}
        result = process_data(data)
        assert result["count"] == 2
        assert "a" in result["keys"]
        assert result["original"] == data


class TestValidateInput:
    def test_string_validation(self):
        assert validate_input("hello", str) is True
        assert validate_input(123, str) is False

    def test_int_validation(self):
        assert validate_input(42, int) is True
        assert validate_input("42", int) is False

    def test_list_validation(self):
        assert validate_input([1, 2], list) is True
        assert validate_input((1, 2), list) is False
""",

            "tests/test_cli.py": """\"\"\"Tests for __PROJECT_NAME__ CLI.\"\"\"

import subprocess
import sys

import pytest


def run_cli(*args: str) -> subprocess.CompletedProcess:
    \"\"\"Run the CLI with given arguments.\"\"\"
    return subprocess.run(
        [sys.executable, "-m", "__PROJECT_NAME_UNDERSCORE__.cli", *args],
        capture_output=True,
        text=True,
    )


class TestCLI:
    def test_version(self):
        result = run_cli("--version")
        assert "0.1.0" in result.stdout

    def test_greet_default(self):
        result = run_cli("greet")
        assert "Hello, World!" in result.stdout

    def test_greet_name(self):
        result = run_cli("greet", "Alice")
        assert "Hello, Alice!" in result.stdout

    def test_greet_json(self):
        result = run_cli("greet", "--json")
        assert '"greeting"' in result.stdout

    def test_process_data(self):
        result = run_cli("process", '{"key": "value"}')
        assert "processed" in result.stdout
""",

            ".gitignore": """__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
.eggs/
*.egg
.env
.venv/
venv/
.mypy_cache/
.pytest_cache/
.coverage
htmlcov/
.ruff_cache/
src/*.egg-info/
""",

            "README.md": """# __PROJECT_NAME__

__DESCRIPTION__

## Installation

```bash
# Install in development mode
pip install -e ".[dev]"
```

## Usage

### Command Line

```bash
# Show help
__PROJECT_NAME_HYPHEN__ --help

# Greet someone
__PROJECT_NAME_HYPHEN__ greet "Alice"

# Process JSON data
__PROJECT_NAME_HYPHEN__ process '{"key": "value"}'
```

### Python API

```python
from __PROJECT_NAME_UNDERSCORE__ import __version__
from __PROJECT_NAME_UNDERSCORE__.core import greet, process_data

print(greet("World"))
result = process_data({"name": "test"})
```

## Development

```bash
# Install dev dependencies
pip install -e ".[dev]"

# Run tests
pytest

# Lint
ruff check src/ tests/

# Type check
mypy src/
```

## Publishing

```bash
python -m build
twine upload dist/*
```
""",
        },
        "post_create_commands": ["pip install -e ."],
        "entry_points": ["src/__PROJECT_NAME_UNDERSCORE__/__init__.py", "src/__PROJECT_NAME_UNDERSCORE__/cli.py"],
    },
}


# ============================================================
# PROJECT SCAFFOLD CLASS
# ============================================================

class ProjectScaffold:
    """Creates complete multi-file project structures from templates.

    The agent can call scaffold_project("nextjs_app", "my-app") and
    generate ALL files at once instead of one file at a time.

    Example:
        scaffold = ProjectScaffold()
        result = scaffold.scaffold_project("nextjs_app", "my-app")
        # result = {"success": True, "files_created": [...], "template": "nextjs_app", ...}
    """

    def __init__(self):
        self.templates = TEMPLATES

    # ----------------------------------------------------------
    # MAIN SCAFFOLD METHOD
    # ----------------------------------------------------------

    def scaffold_project(
        self,
        template_name: str,
        project_name: str,
        target_dir: str = None,
        options: dict = None,
    ) -> dict:
        """Create a complete project from a template.

        Args:
            template_name: Key from TEMPLATES (e.g. "nextjs_app").
            project_name: Name for the new project.
            target_dir: Where to create the project. Defaults to REPOS_DIR/project_name.
            options: Additional options:
                - overwrite (bool): Overwrite existing directory. Default: False.
                - description (str): Project description for README/placeholders.
                - run_post_commands (bool): Run post_create_commands. Default: True.
                - git_init (bool): Initialize git repo. Default: True.

        Returns:
            Dict with: success, files_created, template, project_path, errors
        """
        options = options or {}
        overwrite = options.get("overwrite", False)
        description = options.get("description", "")
        run_post_commands = options.get("run_post_commands", True)
        git_init = options.get("git_init", True)

        # Validate template
        if template_name not in self.templates:
            available = ", ".join(self.templates.keys())
            return {
                "success": False,
                "error": f"Template '{template_name}' not found. Available: {available}",
                "files_created": [],
                "template": None,
                "project_path": None,
            }

        template = self.templates[template_name]

        # Resolve target directory
        if not target_dir:
            target_dir = os.path.join(REPOS_DIR, project_name)

        # Validate path security
        validation = validate_path(target_dir)
        if validation != target_dir:
            return {
                "success": False,
                "error": f"Path validation failed: {validation}",
                "files_created": [],
                "template": template_name,
                "project_path": None,
            }

        # Check if directory exists
        if os.path.exists(target_dir):
            if not overwrite:
                return {
                    "success": False,
                    "error": f"Directory already exists: {target_dir}. Use overwrite=True to replace.",
                    "files_created": [],
                    "template": template_name,
                    "project_path": target_dir,
                }
            logger.warning(f"Overwriting existing directory: {target_dir}")

        # Create files
        files_created = []
        errors = []

        for rel_path, content in template["files"].items():
            # Render placeholders in the file path itself
            rendered_path = _render(rel_path, project_name, description)

            # Render placeholders in the content
            rendered_content = _render(content, project_name, description)

            # Full absolute path
            full_path = os.path.join(target_dir, rendered_path)

            try:
                # Create parent directories
                parent = os.path.dirname(full_path)
                if parent:
                    os.makedirs(parent, exist_ok=True)

                # Write file
                with open(full_path, "w", encoding="utf-8") as f:
                    f.write(rendered_content)

                files_created.append(rendered_path)
                logger.info(f"Created: {rendered_path}")

            except OSError as e:
                error_msg = f"Failed to create {rendered_path}: {e}"
                errors.append(error_msg)
                logger.error(error_msg)

        # Initialize git repo
        if git_init:
            try:
                git_result = subprocess.run(
                    ["git", "init"],
                    capture_output=True,
                    text=True,
                    timeout=15,
                    cwd=target_dir,
                )
                if git_result.returncode == 0:
                    logger.info(f"Git repo initialized in {target_dir}")
                else:
                    logger.warning(f"Git init warning: {git_result.stderr.strip()}")
            except (subprocess.TimeoutExpired, FileNotFoundError) as e:
                logger.warning(f"Git init skipped: {e}")

        # Run post-create commands
        post_commands = template.get("post_create_commands", [])
        post_command_results = []

        if run_post_commands and post_commands:
            for cmd in post_commands:
                logger.info(f"Running post-create command: {cmd}")
                try:
                    if '|' in cmd:
                        # Handle piped commands with chained Popen
                        pipe_segments = cmd.split('|')
                        processes = []
                        prev_stdout = None
                        for i, segment in enumerate(pipe_segments):
                            try:
                                parts = shlex.split(segment.strip())
                            except ValueError:
                                parts = segment.strip().split()
                            if not parts:
                                continue
                            proc = subprocess.Popen(
                                parts, stdin=prev_stdout,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                text=True, cwd=target_dir,
                            )
                            processes.append(proc)
                            if prev_stdout:
                                prev_stdout.close()
                            prev_stdout = proc.stdout
                        stdout, stderr = processes[-1].communicate(timeout=300)
                        for p in processes[:-1]:
                            p.wait(timeout=5)
                        returncode = processes[-1].returncode
                        result = subprocess.CompletedProcess(
                            args=cmd, returncode=returncode,
                            stdout=stdout, stderr=stderr,
                        )
                    else:
                        result = subprocess.run(
                            shlex.split(cmd),
                            capture_output=True,
                            text=True,
                            timeout=300,
                            cwd=target_dir,
                        )
                    post_command_results.append({
                        "command": cmd,
                        "success": result.returncode == 0,
                        "stdout": result.stdout[:500] if result.stdout else "",
                        "stderr": result.stderr[:500] if result.stderr else "",
                    })
                    if result.returncode != 0:
                        logger.warning(f"Post-command '{cmd}' failed: {result.stderr[:200]}")
                    else:
                        logger.info(f"Post-command '{cmd}' completed successfully")
                except subprocess.TimeoutExpired:
                    post_command_results.append({
                        "command": cmd,
                        "success": False,
                        "error": "Command timed out (300s)",
                    })
                    logger.warning(f"Post-command '{cmd}' timed out")

        result = {
            "success": len(files_created) > 0,
            "files_created": files_created,
            "files_count": len(files_created),
            "template": template_name,
            "project_path": target_dir,
            "description": template["description"],
            "entry_points": template.get("entry_points", []),
            "post_command_results": post_command_results,
        }

        if errors:
            result["errors"] = errors

        return result

    # ----------------------------------------------------------
    # LIST TEMPLATES
    # ----------------------------------------------------------

    def list_templates(self) -> dict:
        """Return available templates with descriptions and metadata.

        Returns:
            Dict with templates info and total count.
        """
        templates_info = {}
        for key, tmpl in self.templates.items():
            templates_info[key] = {
                "name": tmpl["name"],
                "description": tmpl["description"],
                "files_count": len(tmpl["files"]),
                "has_post_commands": bool(tmpl.get("post_create_commands")),
                "entry_points": tmpl.get("entry_points", []),
            }

        return {
            "templates": templates_info,
            "total": len(templates_info),
        }

    # ----------------------------------------------------------
    # ADD FILE TO EXISTING PROJECT
    # ----------------------------------------------------------

    def add_file_to_project(
        self,
        project_path: str,
        file_path: str,
        content: str,
    ) -> dict:
        """Add a file to an existing scaffolded project.

        Args:
            project_path: Root directory of the project.
            file_path: Relative path for the new file within the project.
            content: File content to write.

        Returns:
            Dict with success, file_path, absolute_path
        """
        # Validate path
        validation = validate_path(project_path)
        if validation != project_path:
            return {
                "success": False,
                "error": f"Path validation failed: {validation}",
            }

        if not os.path.isdir(project_path):
            return {
                "success": False,
                "error": f"Project directory does not exist: {project_path}",
            }

        full_path = os.path.join(project_path, file_path)

        # Validate the resulting path is still within project
        full_validation = validate_path(full_path)
        if full_validation != full_path:
            return {
                "success": False,
                "error": f"Path validation failed for target: {full_validation}",
            }

        try:
            parent = os.path.dirname(full_path)
            if parent:
                os.makedirs(parent, exist_ok=True)

            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)

            logger.info(f"Added file to project: {file_path}")
            return {
                "success": True,
                "file_path": file_path,
                "absolute_path": full_path,
            }

        except OSError as e:
            return {
                "success": False,
                "error": f"Failed to write file: {e}",
            }

    # ----------------------------------------------------------
    # GENERATE FROM DESCRIPTION (LLM-POWERED)
    # ----------------------------------------------------------

    def generate_from_description(
        self,
        description: str,
        project_name: str,
        target_dir: str = None,
    ) -> dict:
        """Use LLM to generate a custom project structure when no template matches.

        Sends the description to the LLM which returns a JSON structure
        defining the project files, then creates them.

        Args:
            description: Natural language description of the project to create.
            project_name: Name for the new project.
            target_dir: Where to create the project.

        Returns:
            Dict with success, files_created, project_path
        """
        if not target_dir:
            target_dir = os.path.join(REPOS_DIR, project_name)

        # Validate path
        validation = validate_path(target_dir)
        if validation != target_dir:
            return {
                "success": False,
                "error": f"Path validation failed: {validation}",
                "files_created": [],
                "project_path": None,
            }

        # Check if directory exists
        if os.path.exists(target_dir):
            return {
                "success": False,
                "error": f"Directory already exists: {target_dir}",
                "files_created": [],
                "project_path": target_dir,
            }

        # Build LLM prompt
        system_prompt = (
            "You are a project scaffolding assistant. "
            "Given a project description, generate a COMPLETE project structure as JSON.\n\n"
            "Return ONLY a JSON object with this exact format:\n"
            "{\n"
            '  "files": {\n'
            '    "path/to/file.ext": "file content here",\n'
            '    "another/file.py": "import os\\n..."\n'
            "  },\n"
            '  "post_create_commands": ["pip install -r requirements.txt"],\n'
            '  "entry_points": ["main.py"]\n'
            "}\n\n"
            "Rules:\n"
            "- Generate ALL files needed for a working, runnable project\n"
            "- Include package.json or requirements.txt as appropriate\n"
            "- Include README.md with usage instructions\n"
            "- Include .gitignore\n"
            "- File contents must be COMPLETE and FUNCTIONAL, not stubs\n"
            "- Escape newlines in file content as \\n\n"
            "- Return ONLY the JSON, no markdown, no explanation"
        )

        user_prompt = (
            f"Create a project named '{project_name}' with this description:\n"
            f"{description}\n\n"
            "Generate the complete project structure as JSON."
        )

        # Try to use the LLM
        try:
            from llm import ollama

            response = ollama.generate_code([
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ])
        except ImportError:
            response = None
        except Exception as e:
            logger.warning(f"LLM generation failed: {e}")
            response = None

        if not response:
            return {
                "success": False,
                "error": "LLM not available. Use a pre-built template with scaffold_project() instead.",
                "files_created": [],
                "project_path": None,
            }

        # Clean up LLM response (strip markdown code blocks if present)
        response = response.strip()
        if response.startswith("```"):
            response = re.sub(r'^```[a-z]*\n?', '', response)
            response = re.sub(r'\n?```$', '', response)
            response = response.strip()

        # Parse JSON response
        try:
            project_structure = json.loads(response)
        except json.JSONDecodeError as e:
            logger.error(f"LLM returned invalid JSON: {e}")
            return {
                "success": False,
                "error": f"LLM returned invalid JSON: {e}",
                "files_created": [],
                "project_path": None,
                "raw_response": response[:500],
            }

        files = project_structure.get("files", {})
        if not files:
            return {
                "success": False,
                "error": "LLM generated no files",
                "files_created": [],
                "project_path": None,
            }

        # Create the project files
        files_created = []
        errors = []

        for rel_path, content in files.items():
            full_path = os.path.join(target_dir, rel_path)

            # Validate each file path
            path_validation = validate_path(full_path)
            if path_validation != full_path:
                errors.append(f"Path validation failed for: {rel_path}")
                continue

            try:
                parent = os.path.dirname(full_path)
                if parent:
                    os.makedirs(parent, exist_ok=True)

                with open(full_path, "w", encoding="utf-8") as f:
                    f.write(content)

                files_created.append(rel_path)
                logger.info(f"Created (LLM): {rel_path}")

            except OSError as e:
                errors.append(f"Failed to create {rel_path}: {e}")
                logger.error(f"Failed to create {rel_path}: {e}")

        # Initialize git repo
        try:
            subprocess.run(
                ["git", "init"],
                capture_output=True,
                text=True,
                timeout=15,
                cwd=target_dir,
            )
            logger.info(f"Git repo initialized in {target_dir}")
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

        # Run post-create commands
        post_commands = project_structure.get("post_create_commands", [])
        post_command_results = []

        for cmd in post_commands:
            logger.info(f"Running post-create command: {cmd}")
            try:
                if '|' in cmd:
                    # Handle piped commands with chained Popen
                    pipe_segments = cmd.split('|')
                    processes = []
                    prev_stdout = None
                    for i, segment in enumerate(pipe_segments):
                        try:
                            parts = shlex.split(segment.strip())
                        except ValueError:
                            parts = segment.strip().split()
                        if not parts:
                            continue
                        proc = subprocess.Popen(
                            parts, stdin=prev_stdout,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            text=True, cwd=target_dir,
                        )
                        processes.append(proc)
                        if prev_stdout:
                            prev_stdout.close()
                        prev_stdout = proc.stdout
                    stdout, stderr = processes[-1].communicate(timeout=300)
                    for p in processes[:-1]:
                        p.wait(timeout=5)
                    returncode = processes[-1].returncode
                    result = subprocess.CompletedProcess(
                        args=cmd, returncode=returncode,
                        stdout=stdout, stderr=stderr,
                    )
                else:
                    result = subprocess.run(
                        shlex.split(cmd),
                        capture_output=True,
                        text=True,
                        timeout=300,
                        cwd=target_dir,
                    )
                post_command_results.append({
                    "command": cmd,
                    "success": result.returncode == 0,
                })
            except subprocess.TimeoutExpired:
                post_command_results.append({
                    "command": cmd,
                    "success": False,
                    "error": "Timed out",
                })

        result = {
            "success": len(files_created) > 0,
            "files_created": files_created,
            "files_count": len(files_created),
            "project_path": target_dir,
            "template": "custom_llm_generated",
            "entry_points": project_structure.get("entry_points", []),
            "post_command_results": post_command_results,
        }

        if errors:
            result["errors"] = errors

        return result


# ============================================================
# CONVENIENCE FUNCTIONS (for direct import / tool registry)
# ============================================================

def scaffold_project(
    template_name: str,
    project_name: str,
    target_dir: str = None,
    options: dict = None,
) -> dict:
    """Create a project from a template. Convenience wrapper around ProjectScaffold."""
    scaffold = ProjectScaffold()
    return scaffold.scaffold_project(template_name, project_name, target_dir, options)


def list_templates() -> dict:
    """List available project templates."""
    scaffold = ProjectScaffold()
    return scaffold.list_templates()


def add_file_to_project(project_path: str, file_path: str, content: str) -> dict:
    """Add a file to an existing project."""
    scaffold = ProjectScaffold()
    return scaffold.add_file_to_project(project_path, file_path, content)


def generate_from_description(
    description: str,
    project_name: str,
    target_dir: str = None,
) -> dict:
    """Generate a custom project from a natural language description using LLM."""
    scaffold = ProjectScaffold()
    return scaffold.generate_from_description(description, project_name, target_dir)
